---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs02
  labels:
    app: webservice-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webservice-rs
  template:
    metadata:
       labels:
         app: webservice-rs
    spec:
      containers:
        - name: httpd
          image: sachet1994/httpd:v1
...
---
apiVersion: v1
kind: Service
metadata:
  name: rs02-svc #anything
spec:
  type: LoadBalancer
  selector:
    app: webservice-rs
  ports:
  - port: 80
    targetPort: 80
...
